### ISSUE TITLE
Extension does not work anymore.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [igorlogius/handle-with#5]
**Describe the bug**
Hi. I am updating my extensions manually from time to time and I just updated to version from Feb. Unfortunately it does not work any more. In extension debug I see console.log logging the url but then my script is not triggered. Nothing happens.

**To Reproduce**
1. go to page.
2. right click on link
3. select handle with <handler>
4. observe a console.log entry in extension debug window with correct url.
5. nothing happens

**Expected behavior**
Black, command line window appearing and script doing its thing.

**Comment by igorlogius** [comment]
I assume the issue has been resolved, if not, let me know and we can take another look into it.
